# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

import ProjectEuler.utils

size = 100000
triangles = ProjectEuler.utils.get_triangulars(size)
pentagons = ProjectEuler.utils.get_pentagonals(size)
hexagons = ProjectEuler.utils.get_hexagonals(size)

tix = 0
pix = 0

for h in hexagons:
    while triangles[tix] < h and tix < size - 1:
        tix += 1

    if h == triangles[tix]:
        # print("found h in triangles: ", h)

        while pentagons[pix] < h and pix < size - 1:
            pix += 1

        if h == pentagons[pix]:
            print("found hexagonal in triangulars and pentagons: ", h)








